# Generated by Django 5.0 on 2025-09-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_review_like_count_reviewlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
